#!/usr/bin/env node

const exec = require('child_process').exec
const path = require('path')
const sketchtool = path.join(__dirname, 'vendor', 'bin', 'sketchtool')

const args = process.argv.slice(2).join(' ')

exec(`${sketchtool} ${args}`, function(err, stdout, stderr) {
  console.log(stdout)
})
